parameters:
    shopline.designertemplate.entity.class:              Shopline\Bundle\PDFDesignerBundle\Entity\DesignerTemplate
    shopline.designertemplate.datagrid_helper:           Shopline\Bundle\PDFDesignerBundle\Datagrid\DesignerTemplateGridHelper
    shopline.designertemplate.datagrid_view_list.class:  Shopline\Bundle\PDFDesignerBundle\Datagrid\DesignerTemplatesViewList
    shopline.designertemplate.datagrid_helper.class:     Shopline\Bundle\PDFDesignerBundle\Datagrid\DesignerTemplateGridHelper
    shopline.listener.navigation_listener.class:         Shopline\Bundle\PDFDesignerBundle\EventListener\NavigationListener
#    shopline_pdf_designer.example.class: Shopline\Bundle\PDFDesignerBundle\Example
                  
    shopline.body_loader_selector.class:         Shopline\Bundle\PDFDesignerBundle\Provider\DesignerBodyLoaderSelector
    shopline.entity.cache.warmer.class:          Shopline\Bundle\PDFDesignerBundle\Cache\EntityCacheWarmer
    shopline.entity.cache.clearer.class:         Shopline\Bundle\PDFDesignerBundle\Cache\EntityCacheClearer
    shopline.designer.owner.provider.class:         Shopline\Bundle\PDFDesignerBundle\Entity\Provider\DesignerOwnerProvider
    shopline.designer.owner.provider.storage.class: Shopline\Bundle\PDFDesignerBundle\Entity\Provider\DesignerOwnerProviderStorage
    
services:
    shopline.designer.owner.provider.storage:
        public: false
        class: %shopline.designer.owner.provider.storage.class%
        
    shopline.entity.cache.warmer:
        class: %shopline.entity.cache.warmer.class%
        arguments:
            - @shopline.designer.owner.provider.storage
            - %shopline.entity.cache_dir%
            - %shopline.entity.cache_namespace%
            - %shopline.entity.proxy_name_template%
            - @kernel
        tags:
            - { name: kernel.cache_warmer, priority: 30 }

    shopline.entity.cache.clearer:
        class: %shopline.entity.cache.clearer.class%
        arguments:
            - %shopline.entity.cache_dir%
            - %shopline.entity.proxy_name_template%
        tags:
            - { name: kernel.cache_clearer }
    shopline.designer_body_loader_selector:
        public: false
        class: %shopline.body_loader_selector.class%

    shopline.listener.navigation_listener:
        class: %shopline.listener.navigation_listener.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_entity_config.provider.entity
            - @oro_security.security_facade
            - @oro_security.acl_helper
        tags:
            - { name: kernel.event_listener, event: oro_menu.configure.application_menu, method: onNavigationConfigure }

    shopline.designertemplate.datagrid_view_list:
        class: %shopline.designertemplate.datagrid_view_list.class%
        arguments:
            - @translator
    shopline.designertemplate.datagrid_helper:
        class: %shopline.designertemplate.datagrid_helper.class%
        arguments:
            - @oro_entity.entity_provider
            - @translator
