oro_menu_config:
    items:
        shopline_pdfdesigner:
            label: 'shopline.template.title'
            uri:   '#'
            extras:
                position: 300
        shopline_tab_link:
            label: 'shopline.template.manage'
            route: shopline_manage_template
            extras:
                routes: ['/^shopline_manage_template/']
                description: 'shopline.template.manage_template'
    tree:
        application_menu:
            children:
                system_tab:
                    children:
                        shopline_pdfdesigner:
                            children:
                                shopline_tab_link: ~

oro_titles:
    shopline_manage_template: "Manage pdf templates"
    
    
    