parameters:
    shopline.designertemplate.entity.class:              Shopline\Bundle\PDFDesignerBundle\Entity\DesignerTemplate
    shopline.designertemplate.datagrid_helper.class:     Shopline\Bundle\PDFDesignerBundle\Datagrid\DesignerTemplateGridHelper

services:
    shopline.designertemplate.datagrid_helper:
        class: %shopline.designertemplate.datagrid_helper.class%
        arguments:
            - @oro_entity.entity_provider
            - @translator
